version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    ports:
      - "${DB_PORT?err}:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME?err}
      POSTGRES_PASSWORD: ${DB_PASSWORD?err}
      POSTGRES_DB: ${DB_NAME?err}
    volumes:
      - ./data:/var/lib/postgresql/data